// Code generated by protoc-gen-go. DO NOT EDIT.
// source: potato.proto

package potato

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Plan struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Containers           []*Container `protobuf:"bytes,2,rep,name=containers,proto3" json:"containers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Plan) Reset()         { *m = Plan{} }
func (m *Plan) String() string { return proto.CompactTextString(m) }
func (*Plan) ProtoMessage()    {}
func (*Plan) Descriptor() ([]byte, []int) {
	return fileDescriptor_76ce0f17e882bde7, []int{0}
}

func (m *Plan) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Plan.Unmarshal(m, b)
}
func (m *Plan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Plan.Marshal(b, m, deterministic)
}
func (m *Plan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Plan.Merge(m, src)
}
func (m *Plan) XXX_Size() int {
	return xxx_messageInfo_Plan.Size(m)
}
func (m *Plan) XXX_DiscardUnknown() {
	xxx_messageInfo_Plan.DiscardUnknown(m)
}

var xxx_messageInfo_Plan proto.InternalMessageInfo

func (m *Plan) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Plan) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

type Container struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_76ce0f17e882bde7, []int{1}
}

func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (m *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(m, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Plan)(nil), "potato.Plan")
	proto.RegisterType((*Container)(nil), "potato.Container")
}

func init() { proto.RegisterFile("potato.proto", fileDescriptor_76ce0f17e882bde7) }

var fileDescriptor_76ce0f17e882bde7 = []byte{
	// 136 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0xc8, 0x2f, 0x49,
	0x2c, 0xc9, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0x3c, 0xb9, 0x58,
	0x02, 0x72, 0x12, 0xf3, 0x84, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38,
	0x83, 0x98, 0x32, 0x53, 0x84, 0x0c, 0xb9, 0xb8, 0x92, 0xf3, 0xf3, 0x4a, 0x12, 0x33, 0xf3, 0x52,
	0x8b, 0x8a, 0x25, 0x98, 0x14, 0x98, 0x35, 0xb8, 0x8d, 0x04, 0xf5, 0xa0, 0x46, 0x38, 0xc3, 0x64,
	0x82, 0x90, 0x14, 0x29, 0x71, 0x73, 0x71, 0xc2, 0x25, 0x8c, 0x0c, 0xb8, 0xd8, 0x02, 0xc0, 0x8a,
	0x85, 0xd4, 0xb8, 0xd8, 0x82, 0x4b, 0x12, 0x4b, 0x4a, 0x8b, 0x85, 0x78, 0x60, 0xfa, 0x41, 0x36,
	0x4a, 0xa1, 0xf0, 0x94, 0x18, 0x92, 0xd8, 0xc0, 0x0e, 0x33, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff,
	0x3f, 0x0c, 0xfd, 0x5d, 0xa8, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PotatoClient is the client API for Potato service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PotatoClient interface {
	Status(ctx context.Context, in *Plan, opts ...grpc.CallOption) (*Plan, error)
}

type potatoClient struct {
	cc *grpc.ClientConn
}

func NewPotatoClient(cc *grpc.ClientConn) PotatoClient {
	return &potatoClient{cc}
}

func (c *potatoClient) Status(ctx context.Context, in *Plan, opts ...grpc.CallOption) (*Plan, error) {
	out := new(Plan)
	err := c.cc.Invoke(ctx, "/potato.Potato/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PotatoServer is the server API for Potato service.
type PotatoServer interface {
	Status(context.Context, *Plan) (*Plan, error)
}

// UnimplementedPotatoServer can be embedded to have forward compatible implementations.
type UnimplementedPotatoServer struct {
}

func (*UnimplementedPotatoServer) Status(ctx context.Context, req *Plan) (*Plan, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}

func RegisterPotatoServer(s *grpc.Server, srv PotatoServer) {
	s.RegisterService(&_Potato_serviceDesc, srv)
}

func _Potato_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Plan)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PotatoServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/potato.Potato/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PotatoServer).Status(ctx, req.(*Plan))
	}
	return interceptor(ctx, in, info, handler)
}

var _Potato_serviceDesc = grpc.ServiceDesc{
	ServiceName: "potato.Potato",
	HandlerType: (*PotatoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _Potato_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "potato.proto",
}
